package com.ylink.cim.sys.domain;

/**
 * TimerDo generated by MyEclipse Persistence Tools
 */

public class TimerDo implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 1L;
	public static final String INIT = "0";// 初始化
	public static final String BUSINESS_SUCESS = "1";// 业务执行成功
	public static final String BUSINESS_FAILURE = "2";// 业务执行失败
	public static final String CANCEL = "3";// 废弃，下次不用再次执行
	public static final String[] NEED_EXC_STRINGS = {INIT, BUSINESS_FAILURE};
	private String id;

	private String beanName;

	private String beanNameCh;

	private String groupNo;
	private String workdate;

	private String remark;

	private String state;

	private Long para1;
	private String para2;

	private String triggerDate;
	private String triggerTime;

	// Constructors

	/** default constructor */
	public TimerDo() {
	}

	// Property accessors

	public String getBeanName() {
		return this.beanName;
	}

	public String getBeanNameCh() {
		return this.beanNameCh;
	}

	public String getGroupNo() {
		return this.groupNo;
	}

	public Long getPara1() {
		return para1;
	}

	public String getPara2() {
		return para2;
	}

	public String getRemark() {
		return this.remark;
	}

	public String getState() {
		return this.state;
	}

	public String getTriggerDate() {
		return triggerDate;
	}

	public String getTriggerTime() {
		return triggerTime;
	}

	public String getWorkdate() {
		return workdate;
	}

	public void setBeanName(String beanName) {
		this.beanName = beanName;
	}

	public void setBeanNameCh(String beanNameCh) {
		this.beanNameCh = beanNameCh;
	}

	public void setGroupNo(String groupNo) {
		this.groupNo = groupNo;
	}


	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setPara1(Long para1) {
		this.para1 = para1;
	}

	public void setPara2(String para2) {
		this.para2 = para2;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setState(String state) {
		this.state = state;
	}

	public void setTriggerDate(String triggerDate) {
		this.triggerDate = triggerDate;
	}

	public void setTriggerTime(String triggerTime) {
		this.triggerTime = triggerTime;
	}

	public void setWorkdate(String workdate) {
		this.workdate = workdate;
	}

}